### ISSUE TITLE
Can I get the source code

### ISSUE THREAD

**Issue by Nhatcao99** [ekilic/Heatmap-Learner-CNN-for-Object-Counting#1]
This single object detection with heatmap learning. Is this the same idea with the rep https://github.com/littleaich/heatmap-regulation. (regression counting) or detection based counting. 
Can you publish your source code ?

**Comment by ekilic** [comment]
Sorry for late reply. I have added source codes.

**Comment by Nhatcao99** [comment]
thank you for the code

Vào Th 7, 17 thg 7, 2021 vào lúc 04:39 ekilic ***@***.***>
đã viết:
