### ISSUE TITLE
Cannot reproduce the results.

### ISSUE THREAD

**Issue by DaDaPi3** [ekilic/Heatmap-Learner-CNN-for-Object-Counting#2]
Run the test.py with the trained model on the CARPK dataset gave much worse results than reported in the paper.

MAE: 16.21132897603486
RMSE: 31.96154415873697

**Comment by ekilic** [comment]
Could you try again with a set to 0.05 the threshold value at line 63?

**Comment by DaDaPi3** [comment]
Thanks for the suggestion. I tried a few thresholds and still couldn't get the reported results.

MAE = 16.21, RMSE = 31.96 with threshold 0.45. 
MAE = 3.09, RMSE = 4.96 with threshold 0.05.
MAE = 2.87, RMSE = 6.14 with threshold 0.01.
MAE = 3.61, RMSE = 5.11 with threshold 0.1
MAE =  20.00, RMSE = 37.77 with threshold 0.5.

**Comment by ekilic** [comment]
Sorry. There is a error in localizerVgg.py. I set to right parameters in mox pooling layer. Could you update  localizerVgg.py and test it again?

**Comment by DaDaPi3** [comment]
Perfect. I got the same results as reported in the paper. Thank you!

MAE: 2.122004357298475
RMSE: 3.026390819827392
