### ISSUE TITLE
Cannot reproduce the result when training from scratch

### ISSUE THREAD

**Issue by hongvin** [ekilic/Heatmap-Learner-CNN-for-Object-Counting#3]
I tried to run train.py to train from scratch. The result I obtained with test.py is:

```
MAE: 8.969498910675382
RMSE: 17.12831237942957
```

When I try to download the pretrained model and run test.py, the result I obtained are:

```
MAE: 2.122004357298475
RMSE: 3.026390819827392
```

Thank you.

**Comment by ekilic** [comment]
Please check section 4.2 in the paper and use the same parameters for training and data augmentation.

**Comment by Christmas2333** [comment]
> I tried to run train.py to train from scratch. The result I obtained with test.py is:
> 
> ```
> MAE: 8.969498910675382
> RMSE: 17.12831237942957
> ```
> 
> When I try to download the pretrained model and run test.py, the result I obtained are:
> 
> ```
> MAE: 2.122004357298475
> RMSE: 3.026390819827392
> ```
> 
> Thank you.

Hello, have you solved this problem
